if IsClient() then
    require( 'utils/functions_client' )
end

LinkLuaModifier("modifier_birzha_observer", "modifiers/modifier_birzha_observer", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_loser", "modifiers/donate_modifiers/modifier_birzha_loser", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_donater", "modifiers/modifier_birzha_pet", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_illusion_cosmetics", "modifiers/modifier_birzha_dota_modifiers", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_never_reward", "modifiers/birzhapass_modifiers/modifier_bp_never_reward", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_valakas_reward", "modifiers/birzhapass_modifiers/modifier_bp_valakas_reward", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_druzhko_reward", "modifiers/birzhapass_modifiers/modifier_bp_druzhko_reward", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_effects_reward", "modifiers/birzhapass_modifiers/modifier_bp_effects_reward", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_ayano", "modifiers/birzhapass_modifiers/modifier_bp_ayano", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_dangerous_boy", "modifiers/birzhapass_modifiers/modifier_bp_dangerous_boy", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzhapass_sound", "modifiers/modifier_birzhapass_sound", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_gamemode_wtf", "modifiers/modifier_gamemode_wtf", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_sobolev", "modifiers/birzhapass_modifiers/modifier_bp_sobolev", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_mum_arcana", "modifiers/birzhapass_modifiers/modifier_bp_mum_arcana", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_mum_mask", "modifiers/birzhapass_modifiers/modifier_bp_mum_mask", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_dio", "modifiers/birzhapass_modifiers/modifier_bp_dio", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_avatar_persona", "modifiers/birzhapass_modifiers/modifier_avatar_persona", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_pyramide_persona", "modifiers/birzhapass_modifiers/modifier_pyramide_persona", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_sonic_arcana", "modifiers/birzhapass_modifiers/modifier_sonic_arcana", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_bp_johncena", "modifiers/birzhapass_modifiers/modifier_bp_johncena", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_papich_hand_effect", "modifiers/birzhapass_modifiers/modifier_papich_hand_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_map_center_vision", "modifiers/modifier_birzha_map_center_vision.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_generic_knockback_lua", "modifiers/modifier_generic_knockback_lua.lua", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier("modifier_disconnect_debuff", "modifiers/modifier_disconnect_debuff", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_blinoid_shop", "modifiers/modifier_blinoid_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_penguin_shop", "modifiers/modifier_penguin_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_birzha_high_five", "modifiers/modifier_birzha_high_five", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_pet", "modifiers/modifier_birzha_pet", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_premium", "modifiers/donate_modifiers/modifier_birzha_premium", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_vip", "modifiers/donate_modifiers/modifier_birzha_vip", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_gob", "modifiers/donate_modifiers/modifier_birzha_gob", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_dragonball_effect", "modifiers/donate_modifiers/modifier_dragonball_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_leader_effect", "modifiers/donate_modifiers/modifier_leader_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_top_season_13_effect", "modifiers/donate_modifiers/modifier_top_season_13_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_top_season_14_effect", "modifiers/donate_modifiers/modifier_top_season_14_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_top_season_15_effect", "modifiers/donate_modifiers/modifier_top_season_15_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_top_season_16_effect", "modifiers/donate_modifiers/modifier_top_season_16_effect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_effect_hero_diretide", "modifiers/donate_modifiers/modifier_effect_hero_diretide", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_invul", "modifiers/modifier_birzha_dota_modifiers.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_burger_strength", "items/items_burgers", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_burger_agility", "items/items_burgers", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_burger_intellect", "items/items_burgers", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_observer_animation_idle", "modifiers/modifier_birzha_observer", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_observer_animation_sleep", "modifiers/modifier_birzha_observer", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_observer_animation_cast", "modifiers/modifier_birzha_observer", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_map_center_vision_aura", "modifiers/modifier_birzha_map_center_vision.lua", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_penguin_speed", "modifiers/modifier_birzha_start_movespeed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_penguin_caster_zspeed", "modifiers/modifier_birzha_start_movespeed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_blinoid_shop_move", "modifiers/modifier_blinoid_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_generic_knockback_lua", "modifiers/modifier_generic_knockback_lua.lua", LUA_MODIFIER_MOTION_BOTH )
LinkLuaModifier("modifier_blinoid_shop_sound", "modifiers/modifier_blinoid_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_penguin_shop_move", "modifiers/modifier_penguin_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_blinoid_shop_sound", "modifiers/modifier_blinoid_shop", LUA_MODIFIER_MOTION_BOTH)
LinkLuaModifier("modifier_birzha_pet", "modifiers/modifier_birzha_pet.lua", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_disconnect", "modifiers/modifier_birzha_disconnect", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_start_movespeed", "modifiers/modifier_birzha_start_movespeed", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_start_game", "modifiers/modifier_birzha_start_game", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_happy_tank", "modifiers/modifier_birzha_pet", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_illusion_kill", "modifiers/modifier_birzha_illusion_kill", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_gaben_int_fixed", "modifiers/modifier_gaben_int_fixed", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hallowen_birzha_candy", "modifiers/modifier_hallowen_birzha_candy", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_pumpkin_candies_custom", "modifiers/modifier_npc_pumpkin_candies_custom", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_order_cast", "modifiers/modifier_order_cast", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_birzha_fountain_passive", "abilities/units/fountain", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_fountain_passive_invul", "abilities/units/fountain", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_birzha_fountain_attacked", "abilities/units/fountain", LUA_MODIFIER_MOTION_NONE )
LinkLuaModifier("modifier_npc_dota_azazin_antosha", "modifiers/modifier_npc_dota_azazin_antosha", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_dota_azazin_kobold", "modifiers/modifier_npc_dota_azazin_kobold", LUA_MODIFIER_MOTION_NONE)