var heroes = 
{
    "npc_dota_hero_techies": true,
    "npc_dota_hero_abaddon": true,
    "npc_dota_hero_juggernaut": true,
    "npc_dota_hero_sand_king": true,
    "npc_dota_hero_winter_wyvern": true,
    "npc_dota_hero_enigma": true,
    "npc_dota_hero_invoker": true,
    "npc_dota_hero_gyrocopter": true,
    "npc_dota_hero_rubick": true,
    "npc_dota_hero_life_stealer": true,
    "npc_dota_hero_spectre": true,
    "npc_dota_hero_sven": true,
    "npc_dota_hero_naga_siren": true,
    "npc_dota_hero_enchantress": true,
    "npc_dota_hero_phantom_assassin": true,
    "npc_dota_hero_crystal_maiden": true,
    "npc_dota_hero_queenofpain": true,
    "npc_dota_hero_dark_willow": true,
    "npc_dota_hero_templar_assassin": true,
    "npc_dota_hero_lina": true,
    "npc_dota_hero_morphling": true,
    "npc_dota_hero_abyssal_underlord": true,
    "npc_dota_hero_phantom_lancer": true,
    "npc_dota_hero_luna": true,
    "npc_dota_hero_ogre_magi": true,
    "npc_dota_hero_vengefulspirit": true,
    "npc_dota_hero_riki": true,
    "npc_dota_hero_nyx_assassin": true,
    "npc_dota_hero_centaur": true,
    "npc_dota_hero_batrider": true,
    "npc_dota_hero_slardar": true,
    "npc_dota_hero_magnataur": true,
    "npc_dota_hero_treant": true,
    "npc_dota_hero_tidehunter": true,
    "npc_dota_hero_dawnbreaker": true,
    "npc_dota_hero_oracle": true,
    "npc_dota_hero_void_spirit": true,
    "npc_dota_hero_arc_warden": true,
    "npc_dota_hero_sasake": true,
    "npc_dota_hero_migi": true,
    "npc_dota_hero_overlord": true,
    "npc_dota_hero_stone_dwayne": true,
    "npc_dota_hero_silencer": true,
    "npc_dota_hero_marci": true,
    "npc_dota_hero_rat": true,
    "npc_dota_hero_pump": true,
    "npc_dota_hero_pyramide": true,
    "npc_dota_hero_sonic": true,
    "npc_dota_hero_travoman": true,
    "npc_dota_hero_jull": true,
    "npc_dota_hero_nolik": true,
    "npc_dota_hero_freddy": true,
    "npc_dota_hero_saitama": true,
    "npc_dota_hero_tailer": true,
    "npc_dota_hero_thomas_bebra": true,
    "npc_dota_hero_serega_pirat" : true,
    "npc_dota_hero_venom" : true,
    "npc_dota_hero_faceless_void" : true,
    "npc_dota_hero_kelthuzad" : true,
};  

var strength_heroes = 
[
    "npc_dota_hero_huskar",
    "npc_dota_hero_alchemist",
    "npc_dota_hero_slardar",
    "npc_dota_hero_lycan",
    "npc_dota_hero_tusk",
    "npc_dota_hero_saitama",
    "npc_dota_hero_skeleton_king",
    "npc_dota_hero_slark",
    "npc_dota_hero_abaddon",
    "npc_dota_hero_legion_commander",
    "npc_dota_hero_migi",
    "npc_dota_hero_kunkka",
    "npc_dota_hero_pudge",
    "npc_dota_hero_venom",
    "npc_dota_hero_juggernaut",
    "npc_dota_hero_tailer",
    "npc_dota_hero_life_stealer",
    "npc_dota_hero_nolik",
    "npc_dota_hero_pyramide",
    "npc_dota_hero_spirit_breaker",
    "npc_dota_hero_elder_titan",
    "npc_dota_hero_rattletrap",
    "npc_dota_hero_stone_dwayne",
    "npc_dota_hero_mars",
    "npc_dota_hero_brewmaster",
    "npc_dota_hero_beastmaster",
    "npc_dota_hero_axe",
    "npc_dota_hero_treant",
    "npc_dota_hero_tidehunter",
    "npc_dota_hero_spectre",
    "npc_dota_hero_centaur",
    "npc_dota_hero_omniknight",
    "npc_dota_hero_ursa",
    "npc_dota_hero_dark_seer",
    "npc_dota_hero_tiny",
    "npc_dota_hero_earthshaker",
    "npc_dota_hero_sven",
    "npc_dota_hero_bristleback",
    "npc_dota_hero_earth_spirit",
    "npc_dota_hero_chaos_knight",
    "npc_dota_hero_ashab_tamaev",
    "npc_dota_hero_nix_streamer",
]

var agility_heroes = 
[
    "npc_dota_hero_lone_druid",
    "npc_dota_hero_naga_siren",
    "npc_dota_hero_vengefulspirit",
    "npc_dota_hero_ogre_magi",
    "npc_dota_hero_sand_king",
    "npc_dota_hero_pangolier",
    "npc_dota_hero_monkey_king",
    "npc_dota_hero_magnataur",
    "npc_dota_hero_antimage",
    "npc_dota_hero_abyssal_underlord",
    "npc_dota_hero_serega_pirat",
    "npc_dota_hero_queenofpain",
    "npc_dota_hero_marci",
    "npc_dota_hero_dark_willow",
    "npc_dota_hero_furion",
    "npc_dota_hero_sonic",
    "npc_dota_hero_phantom_lancer",
    "npc_dota_hero_nevermore",
    "npc_dota_hero_sasake",
    "npc_dota_hero_terrorblade",
    "npc_dota_hero_batrider",
    "npc_dota_hero_void_spirit",
    "npc_dota_hero_phantom_assassin",
    "npc_dota_hero_arc_warden",
    "npc_dota_hero_luna",
    "npc_dota_hero_bloodseeker",
    "npc_dota_hero_bounty_hunter",
    "npc_dota_hero_dragon_knight",
    "npc_dota_hero_crystal_maiden",
    "npc_dota_hero_winter_wyvern",
    "npc_dota_hero_warlock",
    "npc_dota_hero_rat",
    "npc_dota_hero_sniper",
    "npc_dota_hero_thomas_bebra",
    "npc_dota_hero_ember_spirit",
    "npc_dota_hero_nyx_assassin",
    "npc_dota_hero_troll_warlord",
    "npc_dota_hero_old_god",
]

var intellect_heroes = 
[
    "npc_dota_hero_jull",
    "npc_dota_hero_necrolyte",
    "npc_dota_hero_morphling",
    "npc_dota_hero_enigma",
    "npc_dota_hero_oracle",
    "npc_dota_hero_shredder",
    "npc_dota_hero_templar_assassin",
    "npc_dota_hero_lina",
    "npc_dota_hero_keeper_of_the_light",
    "npc_dota_hero_pump",
    "npc_dota_hero_faceless_void",
    "npc_dota_hero_enchantress",
    "npc_dota_hero_freddy",
    "npc_dota_hero_travoman",
    "npc_dota_hero_gyrocopter",
    "npc_dota_hero_silencer",
    "npc_dota_hero_overlord",
    "npc_dota_hero_dawnbreaker",
    "npc_dota_hero_doom_bringer",
    "npc_dota_hero_puck",
    "npc_dota_hero_invoker",
    "npc_dota_hero_grimstroke",
    "npc_dota_hero_zuus",
    "npc_dota_hero_visage",
    "npc_dota_hero_venomancer",
    "npc_dota_hero_rubick",
    "npc_dota_hero_techies",
    "npc_dota_hero_leshrac",
    "npc_dota_hero_kelthuzad",
]

var heroes_ids = 
{
    npc_dota_hero_antimage: 1,
    npc_dota_hero_axe: 2,
    npc_dota_hero_bane: 3,
    npc_dota_hero_bloodseeker: 4,
    npc_dota_hero_crystal_maiden: 5,
    npc_dota_hero_drow_ranger: 6,
    npc_dota_hero_earthshaker: 7,
    npc_dota_hero_juggernaut: 8,
    npc_dota_hero_mirana: 9,
    npc_dota_hero_nevermore: 11,
    npc_dota_hero_morphling: 10,
    npc_dota_hero_phantom_lancer: 12,
    npc_dota_hero_puck: 13,
    npc_dota_hero_pudge: 14,
    npc_dota_hero_razor: 15,
    npc_dota_hero_sand_king: 16,
    npc_dota_hero_storm_spirit: 17,
    npc_dota_hero_sven: 18,
    npc_dota_hero_tiny: 19,
    npc_dota_hero_vengefulspirit: 20,
    npc_dota_hero_windrunner: 21,
    npc_dota_hero_zuus: 22,
    npc_dota_hero_kunkka: 23,
    npc_dota_hero_lina: 25,
    npc_dota_hero_lich: 31,
    npc_dota_hero_lion: 26,
    npc_dota_hero_shadow_shaman: 27,
    npc_dota_hero_slardar: 28,
    npc_dota_hero_tidehunter: 29,
    npc_dota_hero_witch_doctor: 30,
    npc_dota_hero_riki: 32,
    npc_dota_hero_enigma: 33,
    npc_dota_hero_tinker: 34,
    npc_dota_hero_sniper: 35,
    npc_dota_hero_necrolyte: 36,
    npc_dota_hero_warlock: 37,
    npc_dota_hero_beastmaster: 38,
    npc_dota_hero_queenofpain: 39,
    npc_dota_hero_venomancer: 40,
    npc_dota_hero_faceless_void: 41,
    npc_dota_hero_skeleton_king: 42,
    npc_dota_hero_death_prophet: 43,
    npc_dota_hero_phantom_assassin: 44,
    npc_dota_hero_pugna: 45,
    npc_dota_hero_templar_assassin: 46,
    npc_dota_hero_viper: 47,
    npc_dota_hero_luna: 48,
    npc_dota_hero_dragon_knight: 49,
    npc_dota_hero_dazzle: 50,
    npc_dota_hero_rattletrap: 51,
    npc_dota_hero_leshrac: 52,
    npc_dota_hero_furion: 53,
    npc_dota_hero_life_stealer: 54,
    npc_dota_hero_dark_seer: 55,
    npc_dota_hero_clinkz: 56,
    npc_dota_hero_omniknight: 57,
    npc_dota_hero_enchantress: 58,
    npc_dota_hero_huskar: 59,
    npc_dota_hero_night_stalker: 60,
    npc_dota_hero_broodmother: 61,
    npc_dota_hero_bounty_hunter: 62,
    npc_dota_hero_weaver: 63,
    npc_dota_hero_jakiro: 64,
    npc_dota_hero_batrider: 65,
    npc_dota_hero_chen: 66,
    npc_dota_hero_spectre: 67,
    npc_dota_hero_doom_bringer: 69,
    npc_dota_hero_ancient_apparition: 68,
    npc_dota_hero_ursa: 70,
    npc_dota_hero_spirit_breaker: 71,
    npc_dota_hero_gyrocopter: 72,
    npc_dota_hero_alchemist: 73,
    npc_dota_hero_invoker: 74,
    npc_dota_hero_silencer: 75,
    npc_dota_hero_obsidian_destroyer: 76,
    npc_dota_hero_lycan: 77,
    npc_dota_hero_brewmaster: 78,
    npc_dota_hero_shadow_demon: 79,
    npc_dota_hero_lone_druid: 80,
    npc_dota_hero_chaos_knight: 81,
    npc_dota_hero_meepo: 82,
    npc_dota_hero_treant: 83,
    npc_dota_hero_ogre_magi: 84,
    npc_dota_hero_undying: 85,
    npc_dota_hero_rubick: 86,
    npc_dota_hero_disruptor: 87,
    npc_dota_hero_nyx_assassin: 88,
    npc_dota_hero_naga_siren: 89,
    npc_dota_hero_keeper_of_the_light: 90,
    npc_dota_hero_wisp: 91,
    npc_dota_hero_visage: 92,
    npc_dota_hero_slark: 93,
    npc_dota_hero_medusa: 94,
    npc_dota_hero_troll_warlord: 95,
    npc_dota_hero_centaur: 96,
    npc_dota_hero_magnataur: 97,
    npc_dota_hero_shredder: 98,
    npc_dota_hero_bristleback: 99,
    npc_dota_hero_tusk: 100,
    npc_dota_hero_skywrath_mage: 101,
    npc_dota_hero_abaddon: 102,
    npc_dota_hero_elder_titan: 103,
    npc_dota_hero_legion_commander: 104,
    npc_dota_hero_ember_spirit: 106,
    npc_dota_hero_earth_spirit: 107,
    npc_dota_hero_abyssal_underlord: 108,
    npc_dota_hero_terrorblade: 109,
    npc_dota_hero_phoenix: 110,
    npc_dota_hero_techies: 105,
    npc_dota_hero_oracle: 111,
    npc_dota_hero_winter_wyvern: 112,
    npc_dota_hero_arc_warden: 113,
    npc_dota_hero_monkey_king: 114,
    npc_dota_hero_dark_willow: 119,
    npc_dota_hero_pangolier: 120,
    npc_dota_hero_grimstroke: 121,
    npc_dota_hero_hoodwink: 123,
    npc_dota_hero_void_spirit: 126,
    npc_dota_hero_snapfire: 128,
    npc_dota_hero_mars: 129,
    npc_dota_hero_dawnbreaker: 135,
    npc_dota_hero_marci: 136,
    npc_dota_hero_primal_beast: 137,
    npc_dota_hero_muerta: 138,
    npc_dota_hero_saitama: 180,
    npc_dota_hero_migi: 169,
    npc_dota_hero_venom:184,
    npc_dota_hero_tailer:181,
    npc_dota_hero_nolik:179,
    npc_dota_hero_pyramide:174,
    npc_dota_hero_stone_dwayne:171,
    npc_dota_hero_serega_pirat:183,
    npc_dota_hero_sonic:175,
    npc_dota_hero_sasake:168,
    npc_dota_hero_rat:172,
    npc_dota_hero_thomas_bebra:182,
    npc_dota_hero_jull:177,
    npc_dota_hero_pump:173,
    npc_dota_hero_freddy:178,
    npc_dota_hero_travoman:176,
    npc_dota_hero_overlord:170,
    npc_dota_hero_kelthuzad:185,
    npc_dota_hero_nix_streamer:188,
    npc_dota_hero_ashab_tamaev:189,
    npc_dota_hero_old_god:190,
}

var EFFECTS_LIST =
[
    ["vip", "effect_donater", 259, "vip"], 
    ["premium", "effect_top_donater", 257, "premium"], 
    ["gob", "effect_developer", 258, "gob"], 
    ["dragonball", "effect_unique", 260, "dragonball"], 
    ["season_12", "leader_season_12", 261, "useless"], 
    ["season_13", "leader_season_13", 262, "useless"],
    ["season_14", "leader_season_14", 263, "useless"],
    ["season_15", "leader_season_15", 326, "useless"],
    ["season_16", "leader_season_16", 327, "useless"],
    ["hero_diretide", "hero_diretide", 403, "useless"],
]